### ISSUE TITLE
chromatic 배포 스크립트가 여러번 실행되는 현상

### ISSUE THREAD

**Issue by ppark2ya** [nolmungshemung/ui-kits#21]
## Describe the bug

현재 github packages에 모듈이 배포되는 프로세스가 아래와 같이 순차적으로 실행되고 있는데 크로마틱 배포가 1번, 2번에서 둘 다 실행됌
1. npm 배포
2. github pacakges 배포

**Comment by JuHyerin** [comment]
test-chromatic-workflow

**Comment by JuHyerin** [comment]
test-chromatic-workflow

**Comment by JuHyerin** [comment]
test-chromatic-workflow

**Comment by JuHyerin** [comment]
test-chromatic-workflow

**Comment by JuHyerin** [comment]
test-chromatic-workflow
